export const GET_ERRORS = "GET_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_USERDATA = "GET_USERDATA";
export const UPDATE_USERDATA = "UPDATE_USERDATA";

export const POST_HAPPINESS_BREAKDOWN = "POST_HAPPINESS_BREAKDOWN";
export const POST_HAPPINESS_EVENT = "POST_HAPPINESS_EVENT";
export const UPDATE_HAPPINESS_EVENT = "UPDATE_HAPPINESS_EVENT";

export const POST_TODO = "POST_TODO";
export const POST_TASK = "POST_TASK";
export const POST_SUBTASK = "POST_SUBTASK";
export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TASK = "UPDATE_TASK";
export const UPDATE_SUBTASK = "UPDATE_SUBTASK";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_SUBTASK = "DELETE_SUBTASK";